import Navbar from '@/components/home/navbar';
import { Roboto } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import 'react-image-crop/dist/ReactCrop.css'

const roboto = Roboto({
  weight: ['400', '300', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {

  const session = true

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          {session ? (
            <div className="main flex">
              <Navbar />
              {children}
            </div>
          ) : (
            auth
          )}
        </Providers>
      </body>
    </html>
  );
}
