import Navbar from '@/components/home/navbar';
import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '300', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {
  const isAuth = true;
  return (
    <html lang="en">
      <body className={roboto.className}>
        {isAuth ? (
          <div className="flex">
            <Navbar />
            {children}
          </div>
        ) : (
          auth
        )}
      </body>
    </html>
  );
}
