import Navbar from '@/components/home/navbar';
import './globals.css';
import { Roboto } from 'next/font/google';
import Providers from './providers';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import _ from 'lodash';
import JWTManager from "@/lib/jwt"

const roboto = Roboto({
  weight: ['400', '300', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
}) {

  const session = await getServerSession(authOptions);
  const token = _.get(session, 'token')
  if(token) JWTManager.setToken(token)

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          {session ? (
            <div className="flex">
              <Navbar />
              {children}
            </div>
          ) : (
            auth
          )}
        </Providers>
      </body>
    </html>
  );
}
